import AppKit

/// Classifies pasteboard contents. Pure: no storage, no side effects.
enum ItemExtractor {
    static let maxTextBytes = 1_000_000
    static let maxImagePixels = 50_000_000

    /// nspasteboard.org markers used by password managers and generated content.
    static let privacyMarkerTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    static func extract(from pasteboard: NSPasteboard, pixelLimit: Int = maxImagePixels) -> CapturedItem? {
        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: privacyMarkerTypes) else { return nil }
        // Finder copies (files) are out of scope for v1; their icon TIFF must not be stored.
        guard !types.contains(.fileURL) else { return nil }

        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           let image = image(from: data, pixelLimit: pixelLimit) {
            return image
        }

        let string = pasteboard.string(forType: .string)
            ?? pasteboard.data(forType: .rtf).flatMap { NSAttributedString(rtf: $0, documentAttributes: nil)?.string }
        if let string, !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(truncate(string, maxBytes: maxTextBytes))
        }
        return nil
    }

    private static func image(from data: Data, pixelLimit: Int) -> CapturedItem? {
        guard let size = ImageCoding.pixelSize(of: data),
              size.width * size.height <= pixelLimit,
              let decoded = ImageCoding.decode(data),
              let png = ImageCoding.pngData(from: decoded)
        else { return nil }
        return .image(png: png, width: size.width, height: size.height)
    }

    /// Cuts `string` to at most `maxBytes` UTF-8 bytes without splitting a character.
    static func truncate(_ string: String, maxBytes: Int) -> String {
        guard string.utf8.count > maxBytes else { return string }
        var bytes = 0
        var end = string.startIndex
        for index in string.indices {
            let size = string[index].utf8.count
            if bytes + size > maxBytes { break }
            bytes += size
            end = string.index(after: index)
        }
        return String(string[..<end])
    }
}
