import AppKit
import XCTest
@testable import VzheClip

@MainActor
final class ItemExtractorTests: XCTestCase {
    private func withPasteboard(_ body: (NSPasteboard) throws -> Void) rethrows {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        try body(pasteboard)
    }

    func testPlainText() {
        withPasteboard { pb in
            pb.setString("hello", forType: .string)
            XCTAssertEqual(ItemExtractor.extract(from: pb), .text("hello"))
        }
    }

    func testWhitespaceOnlyTextIsIgnored() {
        withPasteboard { pb in
            pb.setString("  \n\t ", forType: .string)
            XCTAssertNil(ItemExtractor.extract(from: pb))
        }
    }

    func testEmptyPasteboardIsIgnored() {
        withPasteboard { pb in XCTAssertNil(ItemExtractor.extract(from: pb)) }
    }

    func testConcealedAndTransientContentIsIgnored() {
        for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            withPasteboard { pb in
                let markerType = NSPasteboard.PasteboardType(marker)
                pb.declareTypes([.string, markerType], owner: nil)
                pb.setString("secret", forType: .string)
                pb.setData(Data(), forType: markerType)
                XCTAssertNil(ItemExtractor.extract(from: pb), marker)
            }
        }
    }

    func testPNGImage() {
        withPasteboard { pb in
            pb.setData(TestImages.png(width: 30, height: 20), forType: .png)
            guard case .image(let png, let width, let height)? = ItemExtractor.extract(from: pb) else {
                return XCTFail("expected image")
            }
            XCTAssertEqual(width, 30)
            XCTAssertEqual(height, 20)
            XCTAssertNotNil(ImageCoding.decode(png))
        }
    }

    func testTIFFImageIsNormalisedToPNG() throws {
        let tiff = try XCTUnwrap(NSImage(cgImage: TestImages.cgImage(width: 12, height: 8), size: .zero).tiffRepresentation)
        withPasteboard { pb in
            pb.setData(tiff, forType: .tiff)
            guard case .image(let png, 12, 8)? = ItemExtractor.extract(from: pb) else {
                return XCTFail("expected 12x8 image")
            }
            XCTAssertEqual(png.prefix(4), Data([0x89, 0x50, 0x4E, 0x47]), "PNG signature")
        }
    }

    func testImageWinsOverText() {
        withPasteboard { pb in
            pb.declareTypes([.png, .string], owner: nil)
            pb.setData(TestImages.png(width: 5, height: 5), forType: .png)
            pb.setString("https://example.com/cat.png", forType: .string)
            guard case .image? = ItemExtractor.extract(from: pb) else { return XCTFail("expected image") }
        }
    }

    func testOversizedImageFallsBackToText() {
        withPasteboard { pb in
            pb.declareTypes([.png, .string], owner: nil)
            pb.setData(TestImages.png(width: 20, height: 20), forType: .png)
            pb.setString("caption", forType: .string)
            XCTAssertEqual(ItemExtractor.extract(from: pb, pixelLimit: 100), .text("caption"))
        }
    }

    func testOversizedImageAloneIsIgnored() {
        withPasteboard { pb in
            pb.setData(TestImages.png(width: 20, height: 20), forType: .png)
            XCTAssertNil(ItemExtractor.extract(from: pb, pixelLimit: 100))
        }
    }

    // Review Focus #2: Finder puts a file URL and an icon TIFF on the pasteboard.
    func testFinderFileCopyIsIgnored() throws {
        let tiff = try XCTUnwrap(NSImage(cgImage: TestImages.cgImage(width: 16, height: 16), size: .zero).tiffRepresentation)
        withPasteboard { pb in
            pb.declareTypes([.fileURL, .tiff, .string], owner: nil)
            pb.setString("file:///Users/me/report.pdf", forType: .fileURL)
            pb.setData(tiff, forType: .tiff)
            pb.setString("report.pdf", forType: .string)
            XCTAssertNil(ItemExtractor.extract(from: pb))
        }
    }

    func testRTFOnlyIsStoredAsPlainText() throws {
        let rtf = try NSAttributedString(string: "Bold words").data(
            from: NSRange(location: 0, length: 10),
            documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]
        )
        withPasteboard { pb in
            pb.setData(rtf, forType: .rtf)
            XCTAssertEqual(ItemExtractor.extract(from: pb), .text("Bold words"))
        }
    }

    func testLongTextIsTruncated() {
        withPasteboard { pb in
            pb.setString(String(repeating: "a", count: 1_200_000), forType: .string)
            guard case .text(let text)? = ItemExtractor.extract(from: pb) else { return XCTFail("expected text") }
            XCTAssertEqual(text.utf8.count, 1_000_000)
        }
    }

    // Review Focus #4: never split a multi-byte character.
    func testTruncationRespectsCharacterBoundaries() {
        let input = "a" + String(repeating: "😀", count: 300_000)   // 1 + 4 * 300_000 bytes
        let result = ItemExtractor.truncate(input, maxBytes: 1_000_000)
        XCTAssertEqual(result.utf8.count, 999_997)
        XCTAssertEqual(result.last, "😀")
        XCTAssertEqual(ItemExtractor.truncate("short", maxBytes: 1_000_000), "short")
    }
}
